# Generated by cucumber-sinatra. (Fri Jul 09 08:47:29 +0800 2010)

require File.join(File.dirname(__FILE__), '..', '..', 'app/app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'spec'

XPathMaker.set(:environment, :test)

World do
  Capybara.app = XPathMaker
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end
